#!/bin/sh

if [ $# -ne 2 ] ; then
    echo "Usage: pupexplode <pup> <out_dir>"
    echo "pupexplode expands all important files in a PUP and tries to decrypt every file as a self"
    exit 1
fi

pup=$1
outdir=$2

cosunpack $pup $outdir || exit

cd $outdir || exit

cosunpack nand_update nand
cd nand

for f in NAND_UPDATE.pkg.*; do
    unpkg $f ${f}_unpkg || exit
    cat ${f}_unpkg/content >> mega_content.bin || exit
done

cd ..

cosunpack ros coreos
cd coreos

for f in *.pkg; do
	unpkg $f ${f%.pkg}
done

cd ..

cosunpack coreos/CORE_OS_PACKAGE/content coreos/CORE_OS_PACKAGE/

for k in $(find . -name "*.self" -or -name "*.sprx" -or -name "*.isoself" -or -name "*ldr" -or -name "*lv0"); do
	scetool -p ~/data -d $k ${k}.elf
done